backend:
  name: git-gateway

local_backend: true

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

media_library:
  name: "cloudinary"
  output_filename_only: false
  config:
    cloud_name: "livewire-group"
    api_key: "996367731921186"
    default_transformations:
      - - fetch_format: auto # Needs to be an object in and array (i.e. `- -`) because netlify CMS code expecting it
          quality: auto
          crop: scale

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News Post" # Used in the UI, ie.: "New Post"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        media_library:
          config:
            default_transformations:
              - - fetch_format: auto # Needs to be an object in and array (i.e. `- -`) because netlify CMS code expecting it
                  width: 580
                  quality: auto
                  crop: scale
      - { label: "Body", name: "body", widget: "markdown" }
  #  - name: "services"
  #    label: "Services"
  #    folder: "content/services"
  #    create: false
  #    fields:
  #      - { label: "Title", name: "title", widget: "string" }
  #      - { label: "Link Title", name: "linktitle", widget: "string" }
  #      - {
  #          label: "Icon",
  #          name: "icon",
  #          widget: "select",
  #          options: ["promotion", "magnet", "content"],
  #        }
  #      - {
  #          label: "Sections",
  #          name: "sections",
  #          widget: "list",
  #          fields: [{ label: "Text", name: "text", widget: "text" }],
  #        }
  #      - {
  #          label: "Services",
  #          name: "services",
  #          widget: "list",
  #          fields:
  #            [
  #              { label: "Text", name: "text", widget: "text" },
  #              { label: "List", name: "list", widget: "list" },
  #            ],
  #        }
  - name: "pages"
    label: "Pages"
    files:
      - file: "./content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - {
              label: "Intros",
              name: "intros",
              widget: "list",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          #          - {
          #              label: "Services",
          #              name: "services",
          #              widget: "object",
          #              fields:
          #                [
          #                  { label: "Heading", name: "heading", widget: "string" },
          #                  { label: "Text", name: "text", widget: "text" },
          #                  {
          #                    label: "Services",
          #                    name: "services",
          #                    widget: "list",
          #                    fields:
          #                      [
          #                        { label: "Title", name: "title", widget: "string" },
          #                        { label: "Url", name: "url", widget: "string" },
          #                        {
          #                          label: "Icon",
          #                          name: "icon",
          #                          widget: "select",
          #                          options: ["promotion", "magnet", "content"],
          #                        },
          #                      ],
          #                  },
          #                ],
          #            }
          - {
              label: "Brands",
              name: "brands",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  {
                    label: "Logos",
                    name: "logos",
                    widget: "list",
                    fields:
                      [
                        { label: "Name", name: "name", widget: "string" },
                        { label: "Logo", name: "logo", widget: "image", required: false },
                        { label: "Url", name: "url", widget: "string", required: false },
                      ],
                  },
                ],
            }

      - file: "content/gaming-marketing/_index.md"
        label: "Gaming Marketing"
        name: "gaming-marketing"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Link Title", name: linktitle, widget: string }
          - label: "Sections"
            name: sections
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: markdown }
              - { label: Dark, name: dark, widget: boolean }

      - file: "content/gametech/_index.md"
        label: "Gametech"
        name: "gametech"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Link Title", name: linktitle, widget: string }
          - label: "Sections"
            name: sections
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: markdown }
              - { label: Dark, name: dark, widget: boolean }

  - name: "careers" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Job Post" # Used in the UI, ie.: "New Post"
    folder: "content/careers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Employment", name: "employment", widget: "select", options: ["Full Time", "Part Time"] }
      - { label: "Body", name: "body", widget: "markdown" }
#      - file: "content/contact/_index.md"
#        label: "Contact Page"
#        name: "contact"
#        fields:
#          - { label: Title, name: title, widget: string }
#          - { label: Logo, name: logo, widget: image }
#          - { label: Body, name: body, widget: markdown }
#          - label: Contact Entries
#            name: contact_entries
#            widget: list
#            fields:
#              - label: Heading
#                name: heading
#                widget: string
#              - label: Text
#                name: text
#                widget: text
#          - {
#              label: Main,
#              name: main,
#              widget: object,
#              fields:
#                [
#                  { label: Heading, name: heading, widget: string },
#                  { label: Description, name: description, widget: text },
#                  {
#                    label: Image1,
#                    name: image1,
#                    widget: object,
#                    fields:
#                      [
#                        { label: Image, name: image, widget: image },
#                        { label: Alt, name: alt, widget: string },
#                      ],
#                  },
#                  {
#                    label: Image2,
#                    name: image2,
#                    widget: object,
#                    fields:
#                      [
#                        { label: Image, name: image, widget: image },
#                        { label: Alt, name: alt, widget: string },
#                      ],
#                  },
#                  {
#                    label: Image3,
#                    name: image3,
#                    widget: object,
#                    fields:
#                      [
#                        { label: Image, name: image, widget: image },
#                        { label: Alt, name: alt, widget: string },
#                      ],
#                  },
#                ],
#            }
#          - {
#              label: Testimonials,
#              name: testimonials,
#              widget: list,
#              fields:
#                [
#                  { label: Quote, name: quote, widget: string },
#                  { label: Author, name: author, widget: string },
#                ],
#            }
#          - { label: Full_image, name: full_image, widget: image }
#          - {
#              label: Pricing,
#              name: pricing,
#              widget: object,
#              fields:
#                [
#                  { label: Heading, name: heading, widget: string },
#                  { label: Description, name: description, widget: string },
#                  {
#                    label: Plans,
#                    name: plans,
#                    widget: list,
#                    fields:
#                      [
#                        { label: Plan, name: plan, widget: string },
#                        { label: Price, name: price, widget: string },
#                        {
#                          label: Description,
#                          name: description,
#                          widget: string,
#                        },
#                        { label: Items, name: items, widget: list },
#                      ],
#                  },
#                ],
#            }
#      - file: "content/values/_index.md"
#        label: "Values Page"
#        name: "values"
#        fields:
#          - { label: Title, name: title, widget: string }
#          - { label: Image, name: image, widget: image }
#          - label: Values
#            name: values
#            widget: list
#            fields:
#              - { label: Heading, name: heading, widget: string }
#              - { label: Text, name: text, widget: text }
#              - { label: Image, name: imageUrl, widget: image }
